### ISSUE TITLE
auto-delete outdated pch

### ISSUE THREAD

**Issue by Optiligence** [sakra/cotire#97] opened 2016-05-20 13:33 UTC
Working on arch linux with rather frequent compiler updates i get errors about pch files created with a different compiler version. The build fails and i have to manually delete them (or clean rebuild). 
Is it possible to detect this and trigger a rebuild?

**Comment by sakra** [comment] 2016-05-20 14:37
What exactly do you mean by a "clean rebuild" (e.g. "make clean; make"?).
The problem is that triggering a rebuild of the PCH is not enough. If the new compiler version changes the layout of some standard header files (i.e., removes or a renames a standard header), CMake's header dependency scanner will break down. This can only be fixed by re-creating the build folder.

**Comment by Optiligence** [comment] 2016-05-20 14:52
Deleting the pch file in question seems sufficient, which is implicit with `make clean; make`. (i never had to delete my build folder)
It may be a good idea to `make clean; make` with a new compiler anyway, idk. 
I would like a simple `make` (or `ninja` for that matter) to do the right thing™ instead of erroring out and requiring manual intervention.

**Comment by tru** [comment] 2016-08-02 11:05
If you are using `Ninja` this is because CMake doesn't handle `IMPLICIT_DEPENDS` with the Ninja generator. This is usually a problem for us as well, but it seems to require a pretty big patch to CMake to enable.

**Comment by tru** [comment] 2016-08-02 11:05
See also https://github.com/sakra/cotire/issues/21

**Comment by tru** [comment] 2016-08-02 13:14
This was just discussed in the CMake bug-tracker: https://gitlab.kitware.com/cmake/cmake/issues/13234#note_143257

@sakra can you have a look and see if what the Cmake maintainer suggests might be a way forward instead of getting IMPLICIT_DEPENDS in the ninja generator?

**Comment by sakra** [comment] 2016-08-02 18:11
With depfile support in `add_custom_command` it should be possible to integrate cotire better with Ninja.

**Comment by Optiligence** [comment] 2016-08-03 01:17
Although it would be nice to fix this issue too (updated pch deps should trigger pch rebuild for ninja), the problem of updated compiler versions breaking the build is also present with `make`. 
(granted, in GCCs case, it’s header files – which are pch deps – are also updated and therefore trigger a rebuild and workaround the issue in the `make` case but not with ninja due to the other issue)

**Comment by sakra** [comment] 2016-12-08 16:33
Fixed in 1.7.9.

**Closed by sakra** 2016-12-08 16:33 UTC
